### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by TechplexEngineer** [federicobond/python-fseq#1]
Thanks for making this.

Do you know of any higher level tools?
I'd like to play fseq files and broadcast audio using PiFmRds and Falcon Pi Player doesn't seem to allow this.

I'm guessing you made this for a similar reason?

**Comment by federicobond** [comment]
Hi, I haven't investigated the FPP much to give you an answer. This was mostly an experiment in reverse engineering and learning how the format works, now I am mostly doing live audiorhythmic stuff.
